# Generated by Django 3.2.9 on 2022-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220226_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='fighters_counter',
            field=models.IntegerField(default=0, verbose_name='Количество бойцов'),
        ),
        migrations.DeleteModel(
            name='Fighters',
        ),
    ]
