# Generated by Django 3.2.9 on 2022-03-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220316_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='user',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tiltyard',
        ),
        migrations.RemoveField(
            model_name='user',
            name='victoryPoints',
        ),
        migrations.DeleteModel(
            name='Tiltyard',
        ),
    ]
