# Generated by Django 3.2.9 on 2022-03-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220316_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='scores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='victoryPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tiltyard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nomination', models.CharField(max_length=50)),
                ('age_category', models.CharField(max_length=50)),
                ('league', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('stage', models.IntegerField(default=0)),
                ('referee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ристалище',
                'verbose_name_plural': 'Ристалище',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tiltyard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.tiltyard'),
        ),
    ]
