# Generated by Django 3.2.9 on 2022-03-22 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_tiltyard_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiltyard',
            name='age_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tiltyard',
            name='league',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tiltyard',
            name='nomination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tiltyard',
            name='referee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tiltyard',
            name='stage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tiltyard',
            name='state',
            field=models.CharField(blank=True, choices=[('Подготовка', 'Подготовка'), ('Идет', 'Идет'), ('Оконченно', 'Оконченно')], default=1, max_length=50, null=True),
        ),
    ]
