# Generated by Django 3.2.9 on 2022-03-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220317_1436'),
        ('main', '0022_auto_20220323_0120'),
    ]

    operations = [
    ]
