# Generated by Django 3.2.9 on 2022-03-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220331_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.club', verbose_name='Клуб'),
        ),
    ]
