# Generated by Django 3.2.9 on 2022-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_battleorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiltyard',
            name='state',
            field=models.CharField(blank=True, choices=[('Подготовка', 'Подготовка'), ('Идет', 'Идет'), ('Оконченно', 'Оконченно')], default=1, max_length=10, null=True),
        ),
    ]
