# Generated by Django 3.2.9 on 2022-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_tiltyard_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleorder',
            name='stage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='tiltyard',
            name='stage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Этап'),
        ),
    ]
