# Generated by Django 3.2.9 on 2022-04-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220421_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleorder',
            name='stage',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='tiltyard',
            name='stage',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Этап'),
        ),
    ]
