# Generated by Django 3.2.9 on 2022-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20220421_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='scores',
        ),
        migrations.AddField(
            model_name='battleorder',
            name='left_scores',
            field=models.IntegerField(blank=True, default=0, verbose_name='Очки за бой левого бойца'),
        ),
        migrations.AddField(
            model_name='battleorder',
            name='right_scores',
            field=models.IntegerField(blank=True, default=0, verbose_name='Очки за бой правого бойца'),
        ),
    ]
