# Generated by Django 3.2.9 on 2022-05-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_user_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
    ]
