# Generated by Django 3.2.9 on 2022-05-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.IntegerField(choices=[(0, 'Юный боец'), (1, '3 Юнешеский'), (2, '2 Юнешеский'), (3, '1 Юнешеский'), (4, '3 Взрослый'), (5, '2 Взрослый'), (6, '1 Взрослый'), (7, 'КМС'), (8, 'МС'), (9, 'МСМК')], default=0, verbose_name='Категория'),
        ),
    ]
